# Generated by Django 3.2.4 on 2021-07-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Knoeledge',
            new_name='knowledge',
        ),
        migrations.AlterModelOptions(
            name='knowledge',
            options={'verbose_name': 'Knowledge', 'verbose_name_plural': 'Knowledge'},
        ),
    ]
